spring.application.name=demo

# Configuración del Servidor
server.port=8081

# Conexión a Base de Datos (PostgreSQL en Docker)
spring.datasource.url=jdbc:postgresql://localhost:5433/base
spring.datasource.username=admin2
spring.datasource.password=password2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Kafka - PRODUCTOR
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Configuración de Kafka - CONSUMIDOR (Para descontar stock)
spring.kafka.consumer.group-id=inventory-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# HikariPC
spring.datasource.hikari.minimum-idle=5

# Tiempo máximo que Spring esperará por una conexión antes de dar error (30s es mucho, bajamos a 10s)
spring.datasource.hikari.connection-timeout=10000
# Tiempo máximo que una conexión puede estar inactiva en el pool
spring.datasource.hikari.idle-timeout=600000
# Vida máxima de una conexión (evita conexiones "zombis")
spring.datasource.hikari.max-lifetime=1800000
# Número máximo de conexiones abiertas (ajusta según tu tráfico)
spring.datasource.hikari.maximum-pool-size=10


# Kafka Consumer - Ajusta 'concurrency' según tus hilos
spring.kafka.listener.concurrency=3
spring.kafka.producer.acks=all


# Retry: Reintenta 3 veces si la base de datos no responde (PostgreSQL Down)
resilience4j.retry.instances.dbProductos.maxAttempts=3
resilience4j.retry.instances.dbProductos.waitDuration=1s

# Circuit Breaker: Abre el circuito si el 50% de las grabaciones fallan
resilience4j.circuitbreaker.instances.dbProductos.slidingWindowSize=6
resilience4j.circuitbreaker.instances.dbProductos.failureRateThreshold=50
resilience4j.circuitbreaker.instances.dbProductos.waitDurationInOpenState=20s
resilience4j.circuitbreaker.instances.dbProductos.registerHealthIndicator=true

# --- 1. SEGURIDAD ZERO TRUST (OAuth2 / JWT) ---
# Sustituye con la URL de tu proveedor (Keycloak, Auth0, Okta o tu propio server)
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-robgo.us.auth0.com/

# El Identifier de la API (Settings de la API)
spring.security.oauth2.resourceserver.jwt.audiences=https://api-demo-auth0/

# Kafka con SSL/SASL (Evita que alguien lea los mensajes en la red) # SASL_SSL
spring.kafka.properties.security.protocol=PLAINTEXT 
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='admin' password='password';

# --- 3. SERIALIZACIÓN SEGURA PARA KAFKA ---
# Usar JSON Serializer en lugar de String para manejar objetos Producto directamente
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.demo.model

# --- 4. OPTIMIZACIÓN DE RESILIENCIA (Ajustes finales) ---
# Activamos el monitoreo para que el equipo de Ops vea si el circuito se abre
management.health.circuitbreakers.enabled=true
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,resilience4j
























